basePath: /api/v1
definitions:
  models.Data:
    properties:
      item:
        description: 数据信息
        items:
          $ref: '#/definitions/models.Note'
        type: array
      total:
        description: 数据数目
        type: integer
    type: object
  models.Note:
    properties:
      content:
        description: 记录内容
        type: string
      create_time:
        type: integer
      donestatus:
        description: 完成状态
        type: integer
      end_time:
        description: 截止时间
        type: integer
      id:
        type: integer
      start_time:
        type: integer
      title:
        description: 记录题目
        type: string
    type: object
  models.ResponseMessage:
    properties:
      data:
        allOf:
        - $ref: '#/definitions/models.Data'
        description: 数据信息
      err:
        description: 错误信息
        type: string
      msg:
        description: 响应信息
        type: string
      status:
        description: 状态码
        type: integer
    type: object
host: 127.0.0.1:8880
info:
  contact:
    email: support@swagger.io
    name: zhangxin
    url: http://www.swagger.io/support
  description: Golang work.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go-NOTE
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{object}\tModel.ResponseMessage"
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 登录并返回token
  /register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 注册用户名和密码
  /todo:
    delete:
      consumes:
      - application/json
      description: 删除记录
      parameters:
      - description: 完成状态
        in: query
        name: status
        type: integer
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 删除所有/已完成/未完成记录
    get:
      consumes:
      - application/json
      description: 查询记录
      parameters:
      - description: 完成状态
        in: query
        name: status
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 查询所有记录/所有未完成/所有已完成记录
    post:
      consumes:
      - application/json
      description: 添加记录
      parameters:
      - description: 标题
        in: body
        name: title
        schema:
          type: string
      - description: 内容
        in: body
        name: content
        schema:
          type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 添加一条记录
    put:
      consumes:
      - application/json
      description: 更新记录
      parameters:
      - description: 完成状态
        in: query
        name: status
        type: integer
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 更新所有未完成或已完成记录的完成状态
  /todo/{title}:
    delete:
      consumes:
      - application/json
      description: 删除标题为title的记录
      parameters:
      - description: 被删除记录的标题
        in: path
        name: title
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 删除一条记录
    get:
      consumes:
      - application/json
      description: 查询关键词为title的记录
      parameters:
      - description: 标题
        in: path
        name: title
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 查询一条记录
    put:
      consumes:
      - application/json
      description: 更新一条标题为title的记录，状态改为status
      parameters:
      - description: 修改状态
        in: query
        name: status
        required: true
        type: integer
      - description: 被更新记录的标题
        in: path
        name: title
        required: true
        type: string
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: 更新一条记录
swagger: "2.0"
